did correct wrong dates in 2000, corrected url for plots/species
weecology/portal-teachingdb pull request #6
Opened 2018-03-10 13:10 UTC by katrintirok

Hi Ethan,

I noticed that the portal teaching data has a 31st April 2000 and 31st September 2000. When trying to combine year, month, day to a date in python using pd.to_datetime(...) it throughs an error.

I added code to replace those dates with 1st of May and 1st of October 2000, resp., to the create_portal_teaching_dataset.py script and replaced all cvs, json and sqlite files accordingly.

Further, the urls to the species.txt and plots.txt files in the python script did not work, I updated these urls.

How does the data set get updated on figshare?, because I use the figshare link to download data when teaching the Data Carpentry ecology lesson.

Kind Regards
Katrin

2018-03-11 18:51 UTC, ethanwhite requested changes
Thanks @katrintirok! This all looks great. There are a few changes in the `create_portal_teaming_dataset.py` that I think should be removed and I've noted them in-line.

The upload to figshare is still manual. Once you update the `.py` I'll get this merged and update the files on figshare.

2018-03-11 18:51 UTC, ethanwhite commented on create_portal_teaching_dataset.py
> +
This information belongs in the commit message not the file. Unless there's a reason to specific to provide the encoding it shouldn't be included and typically `utf-8` is the default. In short, I think we can just remove this seven line change.

2018-03-11 18:51 UTC, ethanwhite commented on create_portal_teaching_dataset.py
> +# current url (for species and plot table):
I don't think we need the three commented lines here. Let's just fix the url and note the fix in the commit message.

2018-03-11 18:51 UTC, ethanwhite commented on create_portal_teaching_dataset.py
> +# url = "http://wiki.ecologicaldata.org/sites/default/files/portal_plots.txt"
Likewise, drop the comments.

2018-03-11 18:51 UTC, ethanwhite commented on create_portal_teaching_dataset.py
> +# replace wrong dates:
This comment block can be reduced to:
`# Replace invalid dates`

2018-03-12 20:24 UTC, katrintirok commented
@ethanwhite thanks for the review, I changed the python script accordingly. Please check again and let me know when anything else needs to be changed.

2018-03-13 01:28 UTC, ethanwhite commented
Thanks @katrintirok! Looks great. In it goes.

2018-03-13 01:28 UTC, merged

2018-03-13 01:35 UTC, ethanwhite commented
The new files have been uploaded to figshare and should be available at:
https://figshare.com/articles/Portal_Project_Teaching_Database/1314459

When a file gets replaced on figshare it gets a new link, so links in existing material will need to be updated to reflect this change.

Thanks again for catching this and contributing the fixes!

2018-03-14 06:23 UTC, katrintirok commented
Great, I will check all links in the data carpentry lessons for python and R and submit changes accordingly